## Kubernetes service type
service:
  type: ClusterIP
  port: 80

  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:

resources:
  backend:
    cpu: 1000
    memory: 1
  frontend:
    cpu: 1000
    memory: 1
  rabbitmq:
    cpu: 350
    memory: 1
  redis:
    cpu: 350
    memory: 1
  mongodb:
    cpu: 350
    memory: 1

services:
  rabbitmq:
  redis:
    host:
    db:
    port:
    pwd:

env:
  common:
    schedulerLookupInterval:
    unicornWorkers:
    awsS3Region:
    awsS3BucketPrefix:
    awsAccessKeyId:
    awsSecretAccessKey:
    defaultFileStore:
    homePage:
    docsUrl:
    tenantCreationDisabled:
    gmailUsername:
    gmailPassword:
    mailDomain:
    host:
  backend:
    maximumUniconrnConsumers:
    lookupSchedulerOff:
    loadDelayedMessagesOnStart:
  frontend:
    enableRerecaptcha:
    baseMultiplierActiveTasks:
    lookupSchedulerOff:
    delayTasks:
    unicornWorkers:
    baseMultiplierActiveTasks:
