## Docker image reference to deploy.
## -the value of images is the name of base image and the first seven numbers of sha256 checksum of a commit from
## master branch in github-
## default value: latest
## Frontend availables images: https://hub.docker.com/repository/docker/cenitio/frontend/
## Backend availables images: https://hub.docker.com/repository/docker/cenitio/backend/
## Example:
## image:
##   backend:ubuntu-574d627
##   frontend:newrelic-574d627

image:
  deploy: true
  customImage: false
  backend:
    repository:
    replicas:
  frontend:
    repository:
    replicas:
  privateRepository:
    keys:

## Kubernetes service type
service:
  type: ClusterIP
  port: 8080

  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:

## Containers resources
## cpu: 1000 = 1Gb
## cpu: 500 = 0.5Gb
## memory: 1 = 1GB
resources:
  backend:
    cpu: 750
    memory: 1
  frontend:
    cpu: 750
    memory: 1

services:
  csiDrive: false
  rabbitmq:
    deploy: true
    ampqUrl:
    resources:
      cpu: 350
      memory: 1
  redis:
    host:
    db:
    port:
    pwd:
    resources:
      cpu: 350
      memory: 1
  mongodb:
    version:
    database:
    storage:  #Storage are expressed in Gb
    resources:
      cpu:
      memory:
    ui:
      enable:
      cpu:
      memory:
      username:
      pwd:
      ssl:

env:
    ## SMTP configuration
    ##
    ## -default values-
    ## address: smtp.gmail.com
    ## port: 587
    ## domain: cenitsaas.com
    ## authentication: plain
    ## enable_starttls_auto: true
  backend:
    home_page:
    cenit_ui:
    rails_logs_to_stdout:
    skip_initialization:
    scheduler_lookup_interval:
    unicorn_workers:
    maximum_uniconrn_consumers:

    # Optionals Variables
    lookup_scheduler_off:
    base_multiplier_active_tasks:
    oauth_token_end_point:

    # AMAZON SIMPLE STORAGE SERVICE
    aws_s3_region:
    aws_s3_bucket_prefix:
    aws_access_key_id:
    aws_secret_access_key:
    default_file_store:

    # Notifications
    notifier_email:
    exception_recipients:

    # EMAIL CONFIG
    smtp_user_name:
    smtp_password:
    smtp_address:
    smtp_port:
    smtp_domain:
    smtp_authentication:
    smtp_ttls_auto:

  frontend:
    react_app_use_environment_config:
    react_app_timeout_span:
    react_app_app_id:
    react_app_localhost:
    react_app_cenit_host: