## Docker image reference to deploy.
## -the value of image is the first seven numbers of sha256 checksum of a commit from
## master branch in github-
## default value: latest
image:
  backend:
  frontend:


## Kubernetes service type
service:
  type: ClusterIP
  port: 80

  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:

## Containers resources
## cpu: 1000 = 1Gb
## cpu: 500 = 0.5Gb
## memory: 1 = 1GB
resources:
  backend:
    cpu: 750
    memory: 1
  frontend:
    cpu: 750
    memory: 1

services:
  rabbitmq:
    ampqUrl:
    resources:
      cpu: 350
      memory: 1
  redis:
    host:
    db:
    port:
    pwd:
    resources:
      cpu: 350
      memory: 1
  mongodb:
    database:
    storage:  #Storage are expressed in Gb
    resources:
      cpu: 350
      memory: 1

env:
  common:
    schedulerLookupInterval:
    unicornWorkers:
    awsS3Region:
    awsS3BucketPrefix:
    awsAccessKeyId:
    awsSecretAccessKey:
    defaultFileStore:
    homePage:
    docsUrl:
    tenantCreationDisabled:
    host:

    ## SMTP configuration
    ##
    ## -default values-
    ## address: smtp.gmail.com
    ## port: 587
    ## domain: cenitsaas.com
    ## authentication: plain
    ## enable_starttls_auto: true
    smtpConfig:
      address:
      port:
      domain:
      userName:
      password:
      authentication:
      enableStarttlsAuto:

  backend:
    maximumUniconrnConsumers:
    lookupSchedulerOff:
    loadDelayedMessagesOnStart:
  frontend:
    enableRerecaptcha:
    baseMultiplierActiveTasks:
    lookupSchedulerOff:
    delayTasks:
    unicornWorkers:
