{{- if .Values.image.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cenit.fullname" . }}-deployment-backend
spec:
  replicas: {{ default 1 .Values.image.backend.replicas }}
  selector:
    matchLabels:
      platform: {{ template "cenit.fullname" . }}-backend
  template:
    metadata:
      labels:
        platform: {{ template "cenit.fullname" . }}-backend
    spec:
      initContainers:
      - name: init-mongo
        image: busybox:stable
        command: ['sh', '-c', "until nc -z {{ template "cenit.fullname" . }}-mongo-svc 27017; do sleep 30; done;"]
      {{- if not .Values.services.rabbitmq.ampqUrl }}
      - name: init-rabbitmq
        image: busybox:stable
        command: ['sh', '-c', "until nc -z {{ template "cenit.fullname" . }}-rabbitmq-svc 5672; do sleep 30; done;"]
      {{- end }}
      {{- if not .Values.services.redis.host }}
      - name: init-redis
        image: busybox:stable
        command: ['sh', '-c', "until nc -z {{ template "cenit.fullname" . }}-redis-svc 6379; do sleep 30; done;"]
      {{- end }}
      {{- if .Values.image.privateRepository.keys }}
      imagePullSecrets:
        {{- range .Values.image.privateRepository.keys }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ template "cenit.fullname" . }}-backend
      {{- if and .Values.image.customImage .Values.image.backend.repository }}
        image: {{ .Values.image.backend.repository }}
      {{- else }}
        image: cenitio/backend:{{ default "latest" .Values.image.backend.repository }}
      {{- end }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "{{ default 1 .Values.resources.backend.memory }}Gi"
            cpu: "{{ default 1000 .Values.resources.backend.cpu }}m"
        command: ["bundle", "exec", "unicorn", "-c", "config/unicorn.rb"]
        env:
          - name: SKIP_DB_INITIALIZATION
            value: {{ default false .Values.env.backend.skipInitialization | toString | quote  }}
          - name: SCHEDULER_LOOKUP_INTERVAL
            value: {{ default 4 .Values.env.common.schedulerLookupInterval | toString | quote  }}
          - name: UNICORN_WORKERS
            value: {{ default 2 .Values.env.common.unicornWorkers | toString | quote  }}
          - name: MAXIMUM_UNICORN_CONSUMERS
            value: {{ default 2 .Values.env.backend.maximumUniconrnConsumers | toString | quote  }}
          - name: LOOKUP_SCHEDULER_OFF
            value: {{ default false .Values.env.backend.lookupSchedulerOff | toString | quote  }}
          - name: LOAD_DELAYED_MESSAGES_ON_START
            value: {{ default true .Values.env.backend.loadDelayedMessagesOnStart | toString | quote  }}
          - name: BASE_MULTIPLIER_ACTIVE_TASKS
            value: {{ default 50 .Values.env.backend.baseMultiplierActiveTasks | toString | quote }}
          {{- if .Values.env.common.awsS3Region }}
          - name: AWS_S3_REGION
            value: {{ .Values.env.common.awsS3Region | toString | quote  }}
          {{- end }}
          {{- if .Values.env.common.awsS3BucketPrefix }}
          - name: AWS_S3_BUCKET_PREFIX
            value: {{ .Values.env.common.awsS3BucketPrefix | toString | quote  }}
          {{- end }}
          {{- if .Values.env.common.awsAccessKeyId }}
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.env.common.awsAccessKeyId | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.awsSecretAccessKey }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.env.common.awsSecretAccessKey | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.defaultFileStore }}
          - name: DEFAULT_FILE_STORE
            value: {{ .Values.env.common.defaultFileStore | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.homePage }}
          - name: HOMEPAGE
            value: {{ .Values.env.common.homePage | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.docsUrl }}
          - name: DOCS_URL
            value: {{ .Values.env.common.docsUrl | toString | quote }}
          {{- end }}
          - name: TENANT_CREATION_DISABLED
            value: {{ default false .Values.env.common.tenantCreationDisabled | toString | quote }}
          {{- if .Values.env.common.host }}
          - name: HOST
            value: {{ .Values.env.common.host | toString | quote }}
          {{- end }} 
          {{- if and .Values.services.redis.host .Values.services.redis.port .Values.services.redis.db .Values.services.redis.pwd | not }}
          - name: REDIS_HOST
            value: {{ template "cenit.fullname" . }}-redis-svc
          {{- else }}
          - name: REDIS_HOST
            value: {{ .Values.services.redis.host | toString | quote }}
          - name: REDIS_PORT
            value: {{ .Values.services.redis.port | toString | quote }}
          - name: REDIS_DB
            value: {{ .Values.services.redis.db | toString | quote }}
          - name: REDIS_PASSWORD
            value: {{ .Values.services.redis.pwd | toString | quote }}
          {{- end }}
          - name: RABBITMQ_BIGWIG_TX_URL
          {{- if .Values.services.rabbitmq.ampqUrl }}
            value: {{ .Values.services.rabbitmq.ampqUrl }}
          {{- else }}
            value: "amqp://cenit_test:cenit_test@{{ template "cenit.fullname" . }}-rabbitmq-svc/vhost_cenit"
          {{- end }}
          - name: MONGODB_URI
            value: mongodb://{{ template "cenit.fullname" . }}-mongo-svc/{{ default "cenit" .Values.services.mongodb.database }}
          {{- if and .Values.env.common.smtpConfig.userName .Values.env.common.smtpConfig.password }}
          - name: SMTP_USER_NAME
            value: {{ .Values.env.common.smtpConfig.userName | toString | quote }}
          - name: SMTP_PASSWORD
            value: {{ .Values.env.common.smtpConfig.password | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.address }}
          - name: SMTP_ADDRESS
            value: {{ .Values.env.common.smtpConfig.address | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.port }}
          - name: SMTP_PORT
            value: {{ .Values.env.common.smtpConfig.port | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.domain }}
          - name: SMTP_DOMAIN
            value: {{ .Values.env.common.smtpConfig.domain | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.authentication }}
          - name: SMTP_AUTH_TYPE
            value: {{ .Values.env.common.smtpConfig.authentication | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.enableStarttlsAuto }}
          - name: SMTP_TTLS_AUTO
            value: {{ .Values.env.common.smtpConfig.enableStarttlsAuto | toString | quote }}
          {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cenit.fullname" . }}-deployment-frontend
spec:
  replicas: {{ default 1 .Values.image.frontend.replicas }}
  selector:
    matchLabels:
      platform: {{ template "cenit.fullname" . }}-frontend
  template:
    metadata:
      labels:
        platform: {{ template "cenit.fullname" . }}-frontend
    spec:
      initContainers:
      - name: init-mongo
        image: busybox:stable
        command: ['sh', '-c', "until nc -z {{ template "cenit.fullname" . }}-mongo-svc 27017; do sleep 30; done;"]
      {{- if not .Values.services.redis.host }}
      - name: init-redis
        image: busybox:stable
        command: ['sh', '-c', "until nc -z {{ template "cenit.fullname" . }}-redis-svc 6379; do sleep 30; done;"]
      {{- end }}
      {{- if .Values.image.privateRepository.keys }}
      imagePullSecrets:
        {{- range .Values.image.privateRepository.keys }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ template "cenit.fullname" . }}-frontend
      {{- if and .Values.image.customImage .Values.image.frontend.repository }}
        image: {{ .Values.image.frontend.repository }}
      {{- else }}
        image: cenitio/frontend:{{ default "latest" .Values.image.frontend.repository }}
      {{- end }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "{{ default 1 .Values.resources.frontend.memory }}Gi"
            cpu: "{{ default 1000 .Values.resources.frontend.cpu }}m"
        command: ["bundle", "exec", "unicorn", "-c", "config/unicorn.rb"]
        env:
          - name:  MAXIMUM_UNICORN_CONSUMERS
            value: "0"
          - name: SKIP_DB_INITIALIZATION
            value: {{ default false .Values.env.frontend.skipInitialization | toString | quote  }}
          - name: ENABLE_RERECAPTCHA
            value: {{ default false .Values.env.frontend.enableRerecaptcha | toString | quote }}
          - name: SCHEDULER_LOOKUP_INTERVAL
            value: {{ default 4 .Values.env.common.schedulerLookupInterval | toString | quote }}
          - name: UNICORN_WORKERS
            value: {{ default 2 .Values.env.frontend.unicornWorkers | toString | quote }}
          - name: LOOKUP_SCHEDULER_OFF
            value: {{ default true .Values.env.frontend.lookupSchedulerOff | toString | quote }}
          - name: DELAY_TASKS
            value: {{ default true .Values.env.frontend.delayTasks | toString | quote }}
          {{- if and .Values.services.redis.host .Values.services.redis.port .Values.services.redis.db .Values.services.redis.pwd | not }}
          - name: REDIS_HOST
            value: {{ template "cenit.fullname" . }}-redis-svc
          {{- else }}
          - name: REDIS_HOST
            value: {{ .Values.services.redis.host | toString | quote }}
          - name: REDIS_PORT
            value: {{ .Values.services.redis.port | toString | quote }}
          - name: REDIS_DB
            value: {{ .Values.services.redis.db | toString | quote }}
          - name: REDIS_PASSWORD
            value: {{ .Values.services.redis.pwd | toString | quote }}
          {{- end }}
          - name: TENANT_CREATION_DISABLED
            value: {{ default false .Values.env.common.tenantCreationDisabled | toString | quote }}
          - name: MONGODB_URI
            value: mongodb://{{ template "cenit.fullname" . }}-mongo-svc/{{ default "cenit" .Values.services.mongodb.database }}
          {{- if .Values.env.common.awsS3Region }}
          - name: AWS_S3_REGION
            value: {{ .Values.env.common.awsS3Region | toString | quote  }}
          {{- end }}
          {{- if .Values.env.common.awsS3BucketPrefix }}
          - name: AWS_S3_BUCKET_PREFIX
            value: {{ .Values.env.common.awsS3BucketPrefix | toString | quote  }}
          {{- end }}
          {{- if .Values.env.common.awsAccessKeyId }}
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.env.common.awsAccessKeyId | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.awsSecretAccessKey }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.env.common.awsSecretAccessKey | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.defaultFileStore }}
          - name: DEFAULT_FILE_STORE
            value: {{ .Values.env.common.defaultFileStore | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.homePage }}
          - name: HOMEPAGE
            value: {{ .Values.env.common.homePage | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.docsUrl }}
          - name: DOCS_URL
            value: {{ .Values.env.common.docsUrl | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.host }}
          - name: HOST
            value: {{ .Values.env.common.host | toString | quote }}
          {{- end }}
          {{- if and .Values.env.common.smtpConfig.userName .Values.env.common.smtpConfig.password }}
          - name: SMTP_USER_NAME
            value: {{ .Values.env.common.smtpConfig.userName | toString | quote }}
          - name: SMTP_PASSWORD
            value: {{ .Values.env.common.smtpConfig.password | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.address }}
          - name: SMTP_ADDRESS
            value: {{ .Values.env.common.smtpConfig.address | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.port }}
          - name: SMTP_PORT
            value: {{ .Values.env.common.smtpConfig.port | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.domain }}
          - name: SMTP_DOMAIN
            value: {{ .Values.env.common.smtpConfig.domain | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.authentication }}
          - name: SMTP_AUTH_TYPE
            value: {{ .Values.env.common.smtpConfig.authentication | toString | quote }}
          {{- end }}
          {{- if .Values.env.common.smtpConfig.enableStarttlsAuto }}
          - name: SMTP_TTLS_AUTO
            value: {{ .Values.env.common.smtpConfig.enableStarttlsAuto | toString | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
{{- end }}
