apiVersion: v1
kind: Service
metadata:
  name: {{ template "cenit.fullname" . }}-loadbalancer
spec:
  type: LoadBalancer
  selector:
    platform: {{ template "cenit.fullname" . }}-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080