apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cenit.fullname" . }}-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default 1 .Values.services.mongodb.storage }}Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cenit.fullname" . }}-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: {{ template "cenit.fullname" . }}-mongo
  template:
    metadata:
      labels:
        db: {{ template "cenit.fullname" . }}-mongo
    spec:
      volumes:
        - name: {{ template "cenit.fullname" . }}-mongo-storage
          persistentVolumeClaim:
            claimName: {{ template "cenit.fullname" . }}-mongo-pvc
      containers:
      - name: {{ template "cenit.fullname" . }}-mongodb
        image: mongo:3.6
        resources:
          limits:
            memory: "{{ default 1 .Values.services.mongodb.resources.memory }}Gi"
            cpu: "{{ default 350 .Values.services.mongodb.resources.cpu }}m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: {{ template "cenit.fullname" . }}-mongo-storage
            mountPath: /data/db

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "cenit.fullname" . }}-mongo-svc
spec:
  selector:
    db: {{ template "cenit.fullname" . }}-mongo
  ports:
  - port: 27017
    targetPort: 27017
    