{{- if not .Values.services.rabbitmq }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cenit.fullname" . }}-rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cenit.fullname" . }}-rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      amqp: {{ template "cenit.fullname" . }}-rabbitmq
  template:
    metadata:
      labels:
        amqp: {{ template "cenit.fullname" . }}-rabbitmq
    spec:
      volumes:
        - name: {{ template "cenit.fullname" . }}-rabbitmq-storage
          persistentVolumeClaim:
            claimName: {{ template "cenit.fullname" . }}-rabbitmq-pvc
      containers:
      - name: {{ template "cenit.fullname" . }}-rabbitmq
        image: rabbitmq:management
        resources:
          limits:
            memory: "{{ default 1 .Values.resources.rabbitmq.memory }}Gi"
            cpu: "{{ default 350 .Values.resources.rabbitmq.cpu }}m"
        env:
          - name: RABBITMQ_DEFAULT_PASS
            value: "cenit_test"
          - name: RABBITMQ_DEFAULT_USER
            value: "cenit_test"
          - name: RABBITMQ_DEFAULT_VHOST
            value: "vhost_cenit"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
          - name: {{ template "cenit.fullname" . }}-rabbitmq-storage
            mountPath: /var/lib/rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "cenit.fullname" . }}-rabbitmq-svc
spec:
  type: ClusterIP
  selector:
    amqp: {{ template "cenit.fullname" . }}-rabbitmq
  ports:
  - name: consumers-port
    port: 5672
    targetPort: 5672
  - name: gui-port
    port: 15672
    targetPort: 15672

{{- end }}
