apiVersion: v1
kind: Service
metadata:
  name: {{ template "cenit.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: cenit-frontend
    port: {{ .Values.service.port }}
    targetPort: 8080
{{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    platform: {{ template "cenit.fullname" . }}-frontend
